apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-page
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Custom NGINX Page</title>
    <style>
        body {
            background-color: lightblue;
            font-family: Arial, sans-serif;
            text-align: center;
            padding-top: 50px;
        }
    </style>
    </head>
    <body>
        <h1>Hello from my custom NGINX!</h1>
        <p>This page is served by NGINX version: $nginx_version</p>
    </body>
    </html>
